# Generated by Django 5.1.5 on 2025-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fns_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
