# Generated by Django 5.1.5 on 2025-02-23 23:26

import fns_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fns_app', '0002_taxdocument_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to=fns_app.models.xml_upload_path),
        ),
    ]
